version: "3.8"
services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    links:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/canadago
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres

  db:
    image: "postgres:14"
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_DB=canadago
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres